# tekartik analysis_options extension to pedantic
include: package:tekartik_lints/strict.yaml

linter:
  rules:
    depend_on_referenced_packages: false
analyzer:
  # Exclude common build folder.
  exclude:
    - build/**