name: tekartik_build_utils
description: Tekartik app build utilities.
version: 0.7.13
publish_to: none
#author: Alexandre Roux Tekartik <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: ^3.7.0

dependencies:
  tekartik_io_utils:
    git:
      url: https://github.com/tekartik/io_utils.dart
      ref: dart3a
    version: '>=0.5.2'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.5.2'
  tekartik_sc:
    git:
      url: https://github.com/tekartik/sc.dart
      ref: dart3a
    version: '>=0.8.5+1'
  tekartik_pub:
    git:
      url: https://github.com/tekartik/pub.dart
      ref: dart3a
    version: '>=0.10.13'
  tekartik_deploy:
    git:
      url: https://github.com/tekartik/deploy.dart
      ref: dart3a
    version: '>=0.6.2'
    # path: /opt/devx/git/github.com/tekartik/tekartik_deploy.dart
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu_io
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      ref: dart3a
      path: platform_io
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart3a
    version: '>=0.2.4'
  tekartik_app_io_zip:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart3a
      path: packages/app_zip
    version: '>=1.0.1'
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.2"
  grinder: '>=0.9.0-0'
  archive: '>=2.0.13'
  async:

  yaml: ">=3.1.2"
  args: ">=2.6.0"
  fs_shim: ">=2.3.3+1"
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  collection: ">=1.18.0"
  tekartik_prj_tktools:
    git:
      url: https://github.com/tekartikprj/tktools.git
      ref: dart3a
      path: packages/prj_tktools
dev_dependencies:
  test: ">=1.24.0"

#  fs_shim_test:
#    git: https://github.com/tekartik/fs_shim_test.dart
  build_runner: ">=2.4.13"
  build_test: '>=0.10.0'

dependency_overrides:
  archive: '>=4.0.0'
#  tekartik_sc:
#    path: ../sc.dart
#  tekartik_deploy:
#    path: ../deploy.dart
  # fs_shim:
  #  git: https://github.com/tekartik/fs_shim.dart
    # path: /media/ssd/devx/git/github.com/tekartik/fs_shim.dart
  #fs_shim_test:
    # path: /media/ssd/devx/git/github.com/tekartik/fs_shim_test.dart
#  process_run:
    #    git: https://github.com/tekartik/process_run.dart
#    path: ../process_run.dart
#  dev_build:
#    path: ../dev_build.dart/dev_build

executables:
  dpu:
