name: tekartik_build_utils
description: Tekartik app build utilities.
version: 0.0.6
#author: Alexandre Roux Tekartik <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  tekartik_app_utils:
    git: git://github.com/tekartik/tekartik_app_utils.dart
  tekartik_io_utils:
    git: git://github.com/tekartik/tekartik_io_utils.dart
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart
  tekartik_deploy:
    git: git://github.com/tekartik/tekartik_deploy.dart
    # path: /opt/devx/git/github.com/tekartik/tekartik_deploy.dart
  process_run: any
  grinder: any

dev_dependencies:
  test: '>=0.12.0'
  dev_test: any

executables:
  genimg:
dependency_overrides:
#  tekartik_deploy:
#    path: ../tekartik_deploy.dart